name: release

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+-[0-9]+"

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          draft: true
          # (required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}
  upload-assets:
    runs-on: ubuntu-latest
    steps:
      - id: get-upstream-tag
        run: |
          tag=$(echo ${{github.ref_name}} | cut -d- -f1)
          echo "::set-output name=tag::$tag"
      - uses: actions/checkout@v4
        with:
          repository: 'BurntSushi/ripgrep'
          ref: ${{ steps.get-upstream-tag.outputs.tag }}
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install native dependencies
        run: |
          sudo apt update -y
          sudo apt install -y {binutils,gcc}-riscv64-linux-gnu \
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: rg
          build-tool: cargo
          token: ${{ secrets.GITHUB_TOKEN }}
