name: release

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+-[0-9]+"
  pull_request:

permissions:
  contents: write

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: get-upstream-tag
        run: |
          tag=$(echo ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || '$(git describe --tags --abbrev=0)' }} | cut -d- -f1)
          echo "::set-output name=tag::$tag"
      - uses: actions/checkout@v4
        with:
          repository: 'BurntSushi/ripgrep'
          ref: refs/tags/${{ steps.get-upstream-tag.outputs.tag }}
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: riscv64gc-unknown-linux-gnu
      - name: Install native dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y {binutils,gcc}-riscv64-linux-gnu
      - name: Build ripgrep
        env:
          CARGO_TARGET_RISCV64GC_UNKNOWN_LINUX_GNU_LINKER: riscv64-linux-gnu-gcc
        run: |
          cargo build --target riscv64gc-unknown-linux-gnu -F pcre2 --release --bin rg
          mkdir -p out
          mv target/riscv64gc-unknown-linux-gnu/release/rg out/rg
      - name: Strip ripgrep
        run: |
          riscv64-linux-gnu-strip out/rg
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: out/rg
